Imports System
Imports System.Reflection
Imports System.Runtime.InteropServices

' General Information about an assembly is controlled through the following 
' set of attributes. Change these attribute values to modify the information
' associated with an assembly.

' Review the values of the assembly attributes

<Assembly: AssemblyTitle("Siebel Log Analyser")> 
<Assembly: AssemblyDescription("A simple program to read and make sense of Siebel spool files, and log files generated by Siebel client or Server Components. It extracts useful information about SQL/Siebel performance and errors in a table format. Product by crmcog | http://crmcog.com.")> 
<Assembly: AssemblyCompany("")> 
<Assembly: AssemblyProduct("SiebelLogaliser")> 
<Assembly: AssemblyCopyright("Copyright © 2015 crmcog.")> 
<Assembly: AssemblyTrademark("")> 

<Assembly: ComVisible(False)>

'The following GUID is for the ID of the typelib if this project is exposed to COM
<Assembly: Guid("db0075c3-bad9-49bd-b94c-c29c7883bb97")> 

' Version information for an assembly consists of the following four values:
'
'      Major Version
'      Minor Version 
'      Build Number
'      Revision
'
' You can specify all the values or you can default the Build and Revision Numbers 
' by using the '*' as shown below:
' <Assembly: AssemblyVersion("1.0.*")> 

<Assembly: AssemblyVersion("0.0.0.1")> 
<Assembly: AssemblyFileVersion("0.0.0.1")> 
